name: Publish network lists
on:
  push:
    branches: [main]
jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4.2.2
      - name: 🔑 Set up Google Cloud SDK auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: 🔑 Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: 📰 Publish network lists
        env:
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
        run: ./scripts/publish.sh "$GCS_BUCKET_NAME"
