name: Validate
on:
  pull_request:
  push:
    branches: [main]
jobs:
  static-code-analysis:
    runs-on: o1labs-github-arc-runner-ubuntu
    container:
      image: asia-northeast3-docker.pkg.dev/o1labs-192920/gitops-images/github-actions-runner-ubuntu:0.0.1
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4.2.2
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.10.12
      - name: 🔍 Run linting
        uses: pre-commit/action@v3.0.1
