name: Validate
on:
  pull_request:
  push:
    branches: [main]
jobs:
  static-code-analysis:
    runs-on: github-arc-runner
    container:
      image: asia-northeast3-docker.pkg.dev/o1labs-192920/gitops-images/github-actions-runner-ubuntu@sha256:6a057801b698a28307f8135d6fce25d867fe3e8797739845d35ce6e0a33c57c5
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4.2.2
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.10.12
      - name: 🔍 Run linting
        uses: pre-commit/action@v3.0.1
